### ISSUE TITLE
Box for Keynote Speakers and Speakers are not consistent

### ISSUE THREAD

**Issue by tangingw** [pycon-my/pycon-my.github.io#31]
![image](https://github.com/pycon-my/pycon-my.github.io/assets/3361506/7364e696-73f5-45a5-a441-a33600e0f356)

**Comment by amirulabu** [comment]
<img width="1687" alt="Screenshot 2024-03-24 at 9 55 18 AM" src="https://github.com/pycon-my/pycon-my.github.io/assets/10055534/5dfa7325-601e-4939-974b-b4f6bb0f8bde">

My attempt, let me know if it is ok

**Comment by tangingw** [comment]
Keep the style but size to 600 x 400

**Comment by amirulabu** [comment]
https://github.com/pycon-my/pycon-my.github.io/assets/10055534/e576374e-9a61-4926-977f-f8b5f897404a

the size cannot be the same due to it being responsive. the keynote speaker have 2 items per row, the speaker have 3 items per row

**Comment by amirulabu** [comment]
add 10 speakers to "meet our speaker" make it a working carousel
